name: Actualise Data

# runs every monday at 9 am
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./scraper
        run: npm ci
      
      - name: Setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Call scraper
        working-directory: ./scraper
        id: scraper
        run: |
          npm start

          echo "CHARACTERS=$(cat ./output/characters.json)" >> $GITHUB_OUTPUT
          echo "TEAMS=$(cat ./output/teams.json)" >> $GITHUB_OUTPUT
      
      - name: Replace data with actual
        working-directory: ./app
        run:  |
          CHARACTERS_SCRIPT='import type { ICharacterData } from "../types"; export const CHARACTERS: ICharacterData[] = ${{ steps.scraper.outputs.CHARACTERS }};'
          echo $CHARACTERS_SCRIPT > ./src/data/characters.data.ts

          TEAMS_SCRIPT='import type { ITeamData } from "../types"; export const TEAMS: ITeamData[] = ${{ steps.scraper.outputs.TEAMS }};'
          echo $TEAMS_SCRIPT > ./src/data/teams.data.ts

          git add .
          git commit -m "ci: Actualise data"
          git push
        
